"""
Build done_configs.py -- the configs already measured, which the planner skips
when RUNNER has skip_done=True:

    python3 make_done.py ../logs/oracle/80gb/40_20_10_10 [more dirs ...]

Every mig_benchmark_results.csv under the given dirs is read; its model and layout
come from the job.json beside it (smoke runs are skipped). Rows with status ok or
OOM_* count as measured; hang / timeout rows do not, so they run again.
"""

import ast
import csv
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def collect(roots):
    """-> {layout: {model: {split: {(batch, mb), ...}}}}"""
    done = {}
    for root in roots:
        for path in sorted(glob.glob(os.path.join(root, "**", "mig_benchmark_results.csv"), recursive=True)):
            with open(os.path.join(os.path.dirname(path), "job.json")) as f:
                job = json.load(f)
            if job.get("smoke"):
                continue
            layout = "_".join(str(int(g)) for g in job["slice_gb"])
            model = done.setdefault(layout, {}).setdefault(job["model_key"], {})
            with open(path, newline="") as f:
                for r in csv.DictReader(f):
                    if r["status"] == "ok" or r["status"].startswith("OOM_"):
                        split = tuple(ast.literal_eval(r["split"]))
                        model.setdefault(split, set()).add((int(r["batch_size"]), int(r["microbatch_size"])))
    return done


def render(done, roots):
    lines = [f"# Generated by make_done.py from: {' '.join(roots)}",
             "# layout -> model -> split -> (batch, microbatch) pairs already measured.",
             "DONE = {"]
    for layout in sorted(done):
        lines.append(f"    {layout!r}: {{")
        for model in sorted(done[layout]):
            lines.append(f"        {model!r}: {{")
            for split in sorted(done[layout][model]):
                lines.append(f"            {split!r}: {sorted(done[layout][model][split])!r},")
            lines.append("        },")
        lines.append("    },")
    return "\n".join(lines + ["}", ""])


def main(argv):
    if not argv:
        sys.exit(__doc__.strip())
    done = collect(argv)
    out = os.path.join(HERE, "done_configs.py")
    with open(out, "w") as f:
        f.write(render(done, argv))
    for layout, models in sorted(done.items()):
        for model, splits in sorted(models.items()):
            print(f"{layout} {model:12s} {len(splits):3d} splits, {sum(map(len, splits.values()))} configs")
    print(f"-> {out}")


if __name__ == "__main__":
    main(sys.argv[1:])
